name: Deploy docs
on:
  pull_request:
    branches:
      - main

jobs:
  deploy-docs:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      SCOPE: ${{ secrets.SCOPE }}
      PREVIEW_URL: ${{github.event.number}}.web3-connect.pagepreview.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: '0'
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Build preview
        run: pnpm i && pnpm build && cd examples/next-js-example
      - name: Deploy preview
        run: ./scripts/deploy-preview.sh
        working-directory: examples/next-js-example
      - uses: mshick/add-pr-comment@v2
        with:
          message-id: preview-url
          message: |
            | Preview Name | Preview URL |
            | --- | --- |
            | Preview | [${{ env.PREVIEW_URL }}](https://${{ env.PREVIEW_URL }}) |
