name: Test and release
on:
  push:

jobs:
  deploy-docs:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      SCOPE: ${{ secrets.SCOPE }}
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: '0'
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Build preview
        run: pnpm i && pnpm build
      - name: Deploy preview
        run: ./scripts/deploy-prod.sh
        working-directory: examples/next-js-example
        if: ${{ github.ref == 'refs/heads/main' }}
  test:
    if: ${{ github.event.pusher.name != 'github action' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
